import type { Metadata } from "next";
import {
  Inter,
  Sansita_Swashed,
  Spline_Sans,
  Anek_Latin,
  Noto_Sans_Meetei_Mayek,
  Roboto,
} from "next/font/google";
import "./globals.css";

const inter = Roboto({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "sknt.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
